import { access, mkdir } from "node:fs/promises";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { dirname, resolve } from "node:path";

export type JsonObject = Record<string, unknown>;

export type MemlActivation = {
  id: number;
  score: number;
  kind?: string;
  subject?: string;
  predicate?: string;
  object?: string;
  context?: string;
  result?: string;
  confidence?: number;
  signals: Record<string, number>;
};

export type FeedbackAttestation = {
  issuer: string;
  keyId: string;
  nonce: string;
  issuedAt: number;
  expiresAt: number;
  /** Base64-encoded, 64-byte Ed25519 signature generated by the host. */
  signature: string;
};

export type AttestationIssuer = {
  issuer: string;
  keyId: string;
  /** Base64-encoded, 32-byte Ed25519 public key. */
  publicKey: string;
};

export type MemlClientOptions = {
  binary?: string;
  statePath: string;
  /** Explicitly disable lifecycle updates and all feedback writes. Defaults to false. */
  readOnly?: boolean;
  /** Trusted host public keys. Never provide private keys to this client. */
  attestationIssuers?: readonly AttestationIssuer[];
  /** Explicit compatibility escape hatch; do not use for new deployments. */
  legacyReceiptVerifier?: { actor: string; receiptPrefix: string };
};

export type VerifiedExecution = {
  subject: string;
  predicate: string;
  object: string;
  context: string;
  result: string;
  timestamp: number;
  outcome: "success" | "failure";
  failureClass?: string;
  /** Opaque host reference, never a credential. */
  receipt: string;
  /** Optional host label when no proof policy is configured. */
  actor?: string;
  attestation?: FeedbackAttestation;
};

const MAX_REQUEST_BYTES = 60 * 1024;

/** A serialized, long-lived JSONL client for the local MEML CLI. */
export class MemlClient {
  private readonly binary: string;
  private readonly statePath: string;
  private readonly readOnly: boolean;
  private readonly attestationIssuers: readonly AttestationIssuer[];
  private readonly legacyReceiptVerifier?: { actor: string; receiptPrefix: string };
  private process?: ChildProcessWithoutNullStreams;
  private pending = Promise.resolve();
  private stdoutBuffer = "";
  private responses: Array<(line: JsonObject) => void> = [];

  constructor(options: MemlClientOptions) {
    this.binary = options.binary ?? process.env.MEML_BIN ?? resolve(process.cwd(), "zig-out/bin/meml");
    this.statePath = resolve(options.statePath);
    this.readOnly = options.readOnly ?? false;
    this.attestationIssuers = options.attestationIssuers ?? [];
    this.legacyReceiptVerifier = options.legacyReceiptVerifier;
    if (this.readOnly && (this.attestationIssuers.length > 0 || this.legacyReceiptVerifier)) {
      throw new Error("A read-only MEML client cannot configure a feedback verifier");
    }
    if (this.attestationIssuers.length > 0 && this.legacyReceiptVerifier) {
      throw new Error("Configure Ed25519 attestation or the legacy receipt verifier, not both");
    }
  }

  async start(): Promise<void> {
    if (this.process) return;
    await mkdir(dirname(this.statePath), { recursive: true });
    this.process = spawn(this.binary, [], { stdio: ["pipe", "pipe", "pipe"] });
    this.process.stdout.setEncoding("utf8");
    this.process.stdout.on("data", (chunk: string) => this.acceptStdout(chunk));
    this.process.stderr.setEncoding("utf8");
    this.process.once("error", (error) => this.rejectAll(error));
    this.process.once("exit", (code, signal) => {
      this.process = undefined;
      this.rejectAll(new Error(`MEML CLI exited (${signal ?? code ?? "unknown"})`));
    });

    try {
      await this.call({ op: "ping" });
      try {
        await access(this.statePath);
        await this.call({ op: "recover", path: this.statePath });
      } catch (error: unknown) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      }
      await this.configureFeedbackVerifier();
    } catch (error) {
      this.discardProcessState();
      throw error;
    }
  }

  async recall(input: {
    query: string;
    goal?: string;
    situation?: string;
    user?: string;
    limit?: number;
  }): Promise<MemlActivation[]> {
    const response = await this.call({
      op: "activate",
      query: input.query,
      goal: input.goal ?? "",
      situation: input.situation ?? "",
      user: input.user ?? "",
      limit: Math.max(1, Math.min(input.limit ?? 5, 20)),
      details: true,
    });
    return (response.activations ?? []) as MemlActivation[];
  }

  /** Records an outcome; installed proof policies decide whether it must attest. */
  async recordVerifiedExecution(input: VerifiedExecution): Promise<number> {
    if (this.readOnly) throw new Error("This MEML client is read-only");
    const attestation = input.attestation;
    if (this.attestationIssuers.length > 0 && !attestation) {
      throw new Error("A configured Ed25519 MEML client requires a host attestation");
    }
    if (attestation && this.attestationIssuers.length === 0) {
      throw new Error("No Ed25519 attestation issuer is configured for this MEML client");
    }
    if (!attestation && this.legacyReceiptVerifier) this.assertLegacyReceipt(input.receipt);

    const observed = await this.call({
      op: "observe",
      subject: input.subject,
      predicate: input.predicate,
      object: input.object,
      context: input.context,
      result: input.result,
      timestamp: input.timestamp,
    });
    const id = observed.id;
    if (typeof id !== "number") throw new Error("MEML observe response has no numeric id");
    try {
      await this.call({
        op: "feedback",
        target: id,
        outcome: input.outcome,
        failure_class: input.failureClass ?? (input.outcome === "success" ? "none" : "unknown"),
        actor: attestation?.issuer ?? this.legacyReceiptVerifier?.actor ?? input.actor ?? "host",
        receipt: input.receipt,
        timestamp: input.timestamp,
        ...(attestation ? {
          attestation: {
            issuer: attestation.issuer,
            key_id: attestation.keyId,
            nonce: attestation.nonce,
            issued_at: attestation.issuedAt,
            expires_at: attestation.expiresAt,
            signature: attestation.signature,
          },
        } : {}),
      });
    } catch (error) {
      // observe succeeded but feedback failed: discard the unverified in-memory
      // observation rather than serving it to later recalls in this process.
      this.discardProcessState();
      throw error;
    }
    return id;
  }

  /** Default lifecycle updates consolidate and persist. Set readOnly to opt out. */
  async close(): Promise<void> {
    if (!this.process) return;
    try {
      if (!this.readOnly) {
        await this.call({ op: "consolidate", repeat_threshold: 2 });
        await this.call({ op: "persist", path: this.statePath, atomic: true });
      }
    } finally {
      this.discardProcessState();
    }
  }

  private discardProcessState(): void {
    const process = this.process;
    this.process = undefined;
    if (!process) return;
    process.stdin.end();
    process.kill();
  }

  private async configureFeedbackVerifier(): Promise<void> {
    if (this.readOnly) return;
    if (this.attestationIssuers.length > 0) {
      await this.call({
        op: "set_attestation_verifier",
        issuers: this.attestationIssuers.map((issuer) => ({
          issuer: issuer.issuer,
          key_id: issuer.keyId,
          public_key: issuer.publicKey,
        })),
      });
      return;
    }
    if (this.legacyReceiptVerifier) {
      await this.call({
        op: "set_verifier",
        trusted_actors: [this.legacyReceiptVerifier.actor],
        receipt_prefix: this.legacyReceiptVerifier.receiptPrefix,
      });
    }
  }

  private assertLegacyReceipt(receipt: string): void {
    if (!receipt.startsWith(this.legacyReceiptVerifier!.receiptPrefix)) {
      throw new Error(`Verified receipt must start with ${this.legacyReceiptVerifier!.receiptPrefix}`);
    }
  }

  private call(request: JsonObject): Promise<JsonObject> {
    const run = this.pending.then(() => this.writeAndRead(request));
    this.pending = run.then(() => undefined, () => undefined);
    return run;
  }

  private writeAndRead(request: JsonObject): Promise<JsonObject> {
    if (!this.process) throw new Error("MEML client has not been started");
    const line = `${JSON.stringify(request)}\n`;
    if (Buffer.byteLength(line) > MAX_REQUEST_BYTES) throw new Error("MEML request exceeds the 60 KiB integration limit");

    return new Promise<JsonObject>((resolveResponse, rejectResponse) => {
      this.responses.push(resolveResponse);
      this.process!.stdin.write(line, "utf8", (error) => {
        if (!error) return;
        this.responses = this.responses.filter((item) => item !== resolveResponse);
        rejectResponse(error);
      });
    }).then((response) => {
      if (response.ok !== true) throw new Error(`MEML rejected request: ${String(response.error ?? "unknown error")}`);
      return response;
    });
  }

  private acceptStdout(chunk: string): void {
    this.stdoutBuffer += chunk;
    while (true) {
      const newline = this.stdoutBuffer.indexOf("\n");
      if (newline < 0) return;
      const line = this.stdoutBuffer.slice(0, newline);
      this.stdoutBuffer = this.stdoutBuffer.slice(newline + 1);
      const resolveResponse = this.responses.shift();
      if (!resolveResponse || line.length === 0) continue;
      try {
        resolveResponse(JSON.parse(line) as JsonObject);
      } catch {
        this.rejectAll(new Error("MEML CLI emitted invalid JSON"));
      }
    }
  }

  private rejectAll(error: Error): void {
    const pending = this.responses;
    this.responses = [];
    for (const resolveResponse of pending) resolveResponse({ ok: false, error: error.message });
  }
}
