const std = @import("std");

pub const model = @import("model.zig");
pub const backend = @import("backend.zig");
pub const Store = @import("store.zig").Store;
pub const Runtime = @import("runtime.zig").Runtime;
pub const source = @import("source.zig");
pub const storage = @import("storage.zig");
pub const retrieval = @import("retrieval.zig");
pub const persistence = @import("persistence.zig");
pub const index_journal = @import("index_journal.zig");
pub const signals = @import("signals.zig");
pub const neural = @import("neural.zig");
pub const science = @import("science.zig");
pub const quantum = @import("quantum.zig");
pub const evaluation = @import("evaluation.zig");

pub const Kind = model.Kind;
pub const RelationKind = model.RelationKind;
pub const Node = model.Node;
pub const CognitiveState = model.CognitiveState;
pub const TransitionKind = model.TransitionKind;
pub const TransitionInput = model.TransitionInput;
pub const TransitionRecord = model.TransitionRecord;
pub const ActivationPolicy = model.ActivationPolicy;
pub const Relation = model.Relation;
pub const Feedback = source.Feedback;
pub const FeedbackInput = model.FeedbackInput;
pub const FeedbackRecord = model.FeedbackRecord;
pub const FeedbackVerifier = model.FeedbackVerifier;
pub const TransitionVerifier = model.TransitionVerifier;
pub const PlasticityRule = model.PlasticityRule;
pub const PlasticityPolicy = model.PlasticityPolicy;
pub const AttractorState = model.AttractorState;
pub const Stability = model.Stability;
pub const PropagationBudget = model.PropagationBudget;
pub const ProcedurePrediction = model.ProcedurePrediction;
pub const ProcedureSelectionQualityGate = model.ProcedureSelectionQualityGate;
pub const ProcedureSelectionStatus = model.ProcedureSelectionStatus;
pub const ProcedureSelection = model.ProcedureSelection;
pub const ProcedureMetricTarget = model.ProcedureMetricTarget;
pub const ProcedureObjectiveTarget = model.ProcedureObjectiveTarget;
pub const ProcedureObjective = model.ProcedureObjective;
pub const ProcedureComparisonPolicy = model.ProcedureComparisonPolicy;
pub const ProcedureComparisonRejection = model.ProcedureComparisonRejection;
pub const ProcedureObjectiveAssessment = model.ProcedureObjectiveAssessment;
pub const ProcedureComparisonStatus = model.ProcedureComparisonStatus;
pub const ProcedureComparison = model.ProcedureComparison;
pub const AnnotatedCase = evaluation.AnnotatedCase;
pub const AnnotationReport = evaluation.AnnotationReport;
pub const StructuredCase = evaluation.StructuredCase;
pub const StructuredReport = evaluation.StructuredReport;
pub const StructuredQualityGate = evaluation.StructuredQualityGate;
pub const DynamicsCase = evaluation.DynamicsCase;
pub const DynamicsReport = evaluation.DynamicsReport;
pub const ProcedurePredictionCase = evaluation.ProcedurePredictionCase;
pub const ProcedurePredictionReport = evaluation.ProcedurePredictionReport;
pub const ProcedurePredictionQualityGate = evaluation.ProcedurePredictionQualityGate;
pub const ProcedureSelectionCase = evaluation.ProcedureSelectionCase;
pub const ProcedureSelectionReport = evaluation.ProcedureSelectionReport;
pub const ProcedureComparisonCase = evaluation.ProcedureComparisonCase;
pub const ProcedureComparisonReport = evaluation.ProcedureComparisonReport;
pub const Outcome = model.Outcome;
pub const FailureClass = model.FailureClass;
pub const ConsolidationRecord = model.ConsolidationRecord;
pub const FingerprintGroup = model.FingerprintGroup;
pub const FingerprintMember = model.FingerprintMember;
pub const Scope = model.Scope;
pub const Metric = model.Metric;
pub const MetricDirection = model.MetricDirection;
pub const Artifact = model.Artifact;
pub const Structure = model.Structure;
pub const RecordInput = model.RecordInput;
pub const Weights = model.Weights;
pub const Context = model.Context;
pub const Signals = model.Signals;
pub const Activation = model.Activation;
pub const Backend = backend.Backend;
pub const SignalProvider = signals.Provider;
pub const SignalPipeline = signals.Pipeline;

test {
    _ = @import("runtime_test.zig");
    _ = @import("science_test.zig");
}

pub fn main() !void {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer _ = gpa.deinit();
    var threaded: std.Io.Threaded = .init(gpa.allocator(), .{});
    defer threaded.deinit();
    var runtime = Runtime.init(gpa.allocator());
    defer runtime.deinit();
    _ = try runtime.observe("user", "uses", "typescript", "browser", "success", 10);
    _ = try runtime.observe("user", "uses", "python", "data", "success", 20);
    try runtime.addSignalProvider(signals.Metadata.provider());
    try runtime.addSignalProvider(neural.retrievalProvider());
    var activated = try runtime.activate(.{ .query = "uses", .goal = "browser", .situation = "browser", .now = 20 }, 3, gpa.allocator());
    defer activated.deinit(gpa.allocator());
    try runtime.persist(threaded.io(), "meml.state");
    std.debug.print("MEML: activated {d} context-ranked memories\n", .{activated.items.len});
}
